// Code generated by entc, DO NOT EDIT.

package team

import (
	"time"
)

const (
	// Label holds the string label denoting the team type in the database.
	Label = "team"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUlid holds the string denoting the ulid field in the database.
	FieldUlid = "ulid"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldCreateUserID holds the string denoting the create_user_id field in the database.
	FieldCreateUserID = "create_user_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// EdgeCreateUser holds the string denoting the create_user edge name in mutations.
	EdgeCreateUser = "create_user"
	// EdgeTeamUsers holds the string denoting the team_users edge name in mutations.
	EdgeTeamUsers = "team_users"
	// Table holds the table name of the team in the database.
	Table = "teams"
	// CreateUserTable is the table the holds the create_user relation/edge.
	CreateUserTable = "teams"
	// CreateUserInverseTable is the table name for the User model.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	CreateUserInverseTable = "users"
	// CreateUserColumn is the table column denoting the create_user relation/edge.
	CreateUserColumn = "create_user_id"
	// TeamUsersTable is the table the holds the team_users relation/edge.
	TeamUsersTable = "team_users"
	// TeamUsersInverseTable is the table name for the TeamUser model.
	// It exists in this package in order to avoid circular dependency with the "teamuser" package.
	TeamUsersInverseTable = "team_users"
	// TeamUsersColumn is the table column denoting the team_users relation/edge.
	TeamUsersColumn = "team_id"
)

// Columns holds all SQL columns for team fields.
var Columns = []string{
	FieldID,
	FieldUlid,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldCreateUserID,
	FieldName,
	FieldDescription,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)
