// Code generated by MockGen. DO NOT EDIT.
// Source: firebase.go

// Package firebase is a generated GoMock package.
package firebase

import (
	context "context"
	reflect "reflect"

	auth "firebase.google.com/go/v4/auth"
	gomock "github.com/golang/mock/gomock"
)

// MockIFirebaseClient is a mock of IFirebaseClient interface.
type MockIFirebaseClient struct {
	ctrl     *gomock.Controller
	recorder *MockIFirebaseClientMockRecorder
}

// MockIFirebaseClientMockRecorder is the mock recorder for MockIFirebaseClient.
type MockIFirebaseClientMockRecorder struct {
	mock *MockIFirebaseClient
}

// NewMockIFirebaseClient creates a new mock instance.
func NewMockIFirebaseClient(ctrl *gomock.Controller) *MockIFirebaseClient {
	mock := &MockIFirebaseClient{ctrl: ctrl}
	mock.recorder = &MockIFirebaseClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIFirebaseClient) EXPECT() *MockIFirebaseClientMockRecorder {
	return m.recorder
}

// GetUid mocks base method.
func (m *MockIFirebaseClient) GetUid(token *auth.Token) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUid", token)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetUid indicates an expected call of GetUid.
func (mr *MockIFirebaseClientMockRecorder) GetUid(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUid", reflect.TypeOf((*MockIFirebaseClient)(nil).GetUid), token)
}

// VerifyIdToken mocks base method.
func (m *MockIFirebaseClient) VerifyIdToken(ctx context.Context, idToken string) (*auth.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyIdToken", ctx, idToken)
	ret0, _ := ret[0].(*auth.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyIdToken indicates an expected call of VerifyIdToken.
func (mr *MockIFirebaseClientMockRecorder) VerifyIdToken(ctx, idToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyIdToken", reflect.TypeOf((*MockIFirebaseClient)(nil).VerifyIdToken), ctx, idToken)
}
