version: "3.8"
services:
  devcontainer:
    build:
      context: ../
      dockerfile: ./.devcontainer/Dockerfile
    stdin_open: true
    tty: true
    env_file:
      - ../../.env
    volumes:
      - ../../:/go_templete
      - /var/run/docker.sock:/var/run/docker.sock
