// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Khmer495/go-templete/internal/pkg/infrastracture/ent/predicate"
	"github.com/Khmer495/go-templete/internal/pkg/infrastracture/ent/teamuser"
)

// TeamUserDelete is the builder for deleting a TeamUser model.
type TeamUserDelete struct {
	config
	hooks    []Hook
	mutation *TeamUserMutation
}

// Where adds a new predicate to the TeamUserDelete builder.
func (tud *TeamUserDelete) Where(ps ...predicate.TeamUser) *TeamUserDelete {
	tud.mutation.predicates = append(tud.mutation.predicates, ps...)
	return tud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tud *TeamUserDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(tud.hooks) == 0 {
		affected, err = tud.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TeamUserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tud.mutation = mutation
			affected, err = tud.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(tud.hooks) - 1; i >= 0; i-- {
			mut = tud.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tud.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (tud *TeamUserDelete) ExecX(ctx context.Context) int {
	n, err := tud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tud *TeamUserDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: teamuser.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: teamuser.FieldID,
			},
		},
	}
	if ps := tud.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, tud.driver, _spec)
}

// TeamUserDeleteOne is the builder for deleting a single TeamUser model.
type TeamUserDeleteOne struct {
	tud *TeamUserDelete
}

// Exec executes the deletion query.
func (tudo *TeamUserDeleteOne) Exec(ctx context.Context) error {
	n, err := tudo.tud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{teamuser.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tudo *TeamUserDeleteOne) ExecX(ctx context.Context) {
	tudo.tud.ExecX(ctx)
}
