// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Khmer495/go-templete/internal/pkg/infrastracture/ent/predicate"
	"github.com/Khmer495/go-templete/internal/pkg/infrastracture/ent/team"
	"github.com/Khmer495/go-templete/internal/pkg/infrastracture/ent/teamuser"
	"github.com/Khmer495/go-templete/internal/pkg/infrastracture/ent/user"
)

// TeamUserQuery is the builder for querying TeamUser entities.
type TeamUserQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.TeamUser
	// eager-loading edges.
	withTeam *TeamQuery
	withUser *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TeamUserQuery builder.
func (tuq *TeamUserQuery) Where(ps ...predicate.TeamUser) *TeamUserQuery {
	tuq.predicates = append(tuq.predicates, ps...)
	return tuq
}

// Limit adds a limit step to the query.
func (tuq *TeamUserQuery) Limit(limit int) *TeamUserQuery {
	tuq.limit = &limit
	return tuq
}

// Offset adds an offset step to the query.
func (tuq *TeamUserQuery) Offset(offset int) *TeamUserQuery {
	tuq.offset = &offset
	return tuq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tuq *TeamUserQuery) Unique(unique bool) *TeamUserQuery {
	tuq.unique = &unique
	return tuq
}

// Order adds an order step to the query.
func (tuq *TeamUserQuery) Order(o ...OrderFunc) *TeamUserQuery {
	tuq.order = append(tuq.order, o...)
	return tuq
}

// QueryTeam chains the current query on the "team" edge.
func (tuq *TeamUserQuery) QueryTeam() *TeamQuery {
	query := &TeamQuery{config: tuq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tuq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tuq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(teamuser.Table, teamuser.FieldID, selector),
			sqlgraph.To(team.Table, team.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, teamuser.TeamTable, teamuser.TeamColumn),
		)
		fromU = sqlgraph.SetNeighbors(tuq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (tuq *TeamUserQuery) QueryUser() *UserQuery {
	query := &UserQuery{config: tuq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tuq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tuq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(teamuser.Table, teamuser.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, teamuser.UserTable, teamuser.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(tuq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TeamUser entity from the query.
// Returns a *NotFoundError when no TeamUser was found.
func (tuq *TeamUserQuery) First(ctx context.Context) (*TeamUser, error) {
	nodes, err := tuq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{teamuser.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tuq *TeamUserQuery) FirstX(ctx context.Context) *TeamUser {
	node, err := tuq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TeamUser ID from the query.
// Returns a *NotFoundError when no TeamUser ID was found.
func (tuq *TeamUserQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tuq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{teamuser.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tuq *TeamUserQuery) FirstIDX(ctx context.Context) int {
	id, err := tuq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TeamUser entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one TeamUser entity is not found.
// Returns a *NotFoundError when no TeamUser entities are found.
func (tuq *TeamUserQuery) Only(ctx context.Context) (*TeamUser, error) {
	nodes, err := tuq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{teamuser.Label}
	default:
		return nil, &NotSingularError{teamuser.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tuq *TeamUserQuery) OnlyX(ctx context.Context) *TeamUser {
	node, err := tuq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TeamUser ID in the query.
// Returns a *NotSingularError when exactly one TeamUser ID is not found.
// Returns a *NotFoundError when no entities are found.
func (tuq *TeamUserQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tuq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{teamuser.Label}
	default:
		err = &NotSingularError{teamuser.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tuq *TeamUserQuery) OnlyIDX(ctx context.Context) int {
	id, err := tuq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TeamUsers.
func (tuq *TeamUserQuery) All(ctx context.Context) ([]*TeamUser, error) {
	if err := tuq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return tuq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (tuq *TeamUserQuery) AllX(ctx context.Context) []*TeamUser {
	nodes, err := tuq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TeamUser IDs.
func (tuq *TeamUserQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := tuq.Select(teamuser.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tuq *TeamUserQuery) IDsX(ctx context.Context) []int {
	ids, err := tuq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tuq *TeamUserQuery) Count(ctx context.Context) (int, error) {
	if err := tuq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return tuq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (tuq *TeamUserQuery) CountX(ctx context.Context) int {
	count, err := tuq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tuq *TeamUserQuery) Exist(ctx context.Context) (bool, error) {
	if err := tuq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return tuq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (tuq *TeamUserQuery) ExistX(ctx context.Context) bool {
	exist, err := tuq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TeamUserQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tuq *TeamUserQuery) Clone() *TeamUserQuery {
	if tuq == nil {
		return nil
	}
	return &TeamUserQuery{
		config:     tuq.config,
		limit:      tuq.limit,
		offset:     tuq.offset,
		order:      append([]OrderFunc{}, tuq.order...),
		predicates: append([]predicate.TeamUser{}, tuq.predicates...),
		withTeam:   tuq.withTeam.Clone(),
		withUser:   tuq.withUser.Clone(),
		// clone intermediate query.
		sql:  tuq.sql.Clone(),
		path: tuq.path,
	}
}

// WithTeam tells the query-builder to eager-load the nodes that are connected to
// the "team" edge. The optional arguments are used to configure the query builder of the edge.
func (tuq *TeamUserQuery) WithTeam(opts ...func(*TeamQuery)) *TeamUserQuery {
	query := &TeamQuery{config: tuq.config}
	for _, opt := range opts {
		opt(query)
	}
	tuq.withTeam = query
	return tuq
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (tuq *TeamUserQuery) WithUser(opts ...func(*UserQuery)) *TeamUserQuery {
	query := &UserQuery{config: tuq.config}
	for _, opt := range opts {
		opt(query)
	}
	tuq.withUser = query
	return tuq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TeamUser.Query().
//		GroupBy(teamuser.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (tuq *TeamUserQuery) GroupBy(field string, fields ...string) *TeamUserGroupBy {
	group := &TeamUserGroupBy{config: tuq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := tuq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return tuq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.TeamUser.Query().
//		Select(teamuser.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (tuq *TeamUserQuery) Select(field string, fields ...string) *TeamUserSelect {
	tuq.fields = append([]string{field}, fields...)
	return &TeamUserSelect{TeamUserQuery: tuq}
}

func (tuq *TeamUserQuery) prepareQuery(ctx context.Context) error {
	for _, f := range tuq.fields {
		if !teamuser.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tuq.path != nil {
		prev, err := tuq.path(ctx)
		if err != nil {
			return err
		}
		tuq.sql = prev
	}
	return nil
}

func (tuq *TeamUserQuery) sqlAll(ctx context.Context) ([]*TeamUser, error) {
	var (
		nodes       = []*TeamUser{}
		_spec       = tuq.querySpec()
		loadedTypes = [2]bool{
			tuq.withTeam != nil,
			tuq.withUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &TeamUser{config: tuq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, tuq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := tuq.withTeam; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*TeamUser)
		for i := range nodes {
			fk := nodes[i].TeamID
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(team.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "team_id" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Team = n
			}
		}
	}

	if query := tuq.withUser; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*TeamUser)
		for i := range nodes {
			fk := nodes[i].UserID
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(user.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.User = n
			}
		}
	}

	return nodes, nil
}

func (tuq *TeamUserQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tuq.querySpec()
	return sqlgraph.CountNodes(ctx, tuq.driver, _spec)
}

func (tuq *TeamUserQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := tuq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (tuq *TeamUserQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   teamuser.Table,
			Columns: teamuser.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: teamuser.FieldID,
			},
		},
		From:   tuq.sql,
		Unique: true,
	}
	if unique := tuq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := tuq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, teamuser.FieldID)
		for i := range fields {
			if fields[i] != teamuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tuq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tuq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tuq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tuq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tuq *TeamUserQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tuq.driver.Dialect())
	t1 := builder.Table(teamuser.Table)
	selector := builder.Select(t1.Columns(teamuser.Columns...)...).From(t1)
	if tuq.sql != nil {
		selector = tuq.sql
		selector.Select(selector.Columns(teamuser.Columns...)...)
	}
	for _, p := range tuq.predicates {
		p(selector)
	}
	for _, p := range tuq.order {
		p(selector)
	}
	if offset := tuq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tuq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TeamUserGroupBy is the group-by builder for TeamUser entities.
type TeamUserGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tugb *TeamUserGroupBy) Aggregate(fns ...AggregateFunc) *TeamUserGroupBy {
	tugb.fns = append(tugb.fns, fns...)
	return tugb
}

// Scan applies the group-by query and scans the result into the given value.
func (tugb *TeamUserGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := tugb.path(ctx)
	if err != nil {
		return err
	}
	tugb.sql = query
	return tugb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (tugb *TeamUserGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := tugb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (tugb *TeamUserGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(tugb.fields) > 1 {
		return nil, errors.New("ent: TeamUserGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := tugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (tugb *TeamUserGroupBy) StringsX(ctx context.Context) []string {
	v, err := tugb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tugb *TeamUserGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = tugb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{teamuser.Label}
	default:
		err = fmt.Errorf("ent: TeamUserGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (tugb *TeamUserGroupBy) StringX(ctx context.Context) string {
	v, err := tugb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (tugb *TeamUserGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(tugb.fields) > 1 {
		return nil, errors.New("ent: TeamUserGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := tugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (tugb *TeamUserGroupBy) IntsX(ctx context.Context) []int {
	v, err := tugb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tugb *TeamUserGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = tugb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{teamuser.Label}
	default:
		err = fmt.Errorf("ent: TeamUserGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (tugb *TeamUserGroupBy) IntX(ctx context.Context) int {
	v, err := tugb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (tugb *TeamUserGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(tugb.fields) > 1 {
		return nil, errors.New("ent: TeamUserGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := tugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (tugb *TeamUserGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := tugb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tugb *TeamUserGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = tugb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{teamuser.Label}
	default:
		err = fmt.Errorf("ent: TeamUserGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (tugb *TeamUserGroupBy) Float64X(ctx context.Context) float64 {
	v, err := tugb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (tugb *TeamUserGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(tugb.fields) > 1 {
		return nil, errors.New("ent: TeamUserGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := tugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (tugb *TeamUserGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := tugb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tugb *TeamUserGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = tugb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{teamuser.Label}
	default:
		err = fmt.Errorf("ent: TeamUserGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (tugb *TeamUserGroupBy) BoolX(ctx context.Context) bool {
	v, err := tugb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tugb *TeamUserGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range tugb.fields {
		if !teamuser.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := tugb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tugb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (tugb *TeamUserGroupBy) sqlQuery() *sql.Selector {
	selector := tugb.sql
	columns := make([]string, 0, len(tugb.fields)+len(tugb.fns))
	columns = append(columns, tugb.fields...)
	for _, fn := range tugb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(tugb.fields...)
}

// TeamUserSelect is the builder for selecting fields of TeamUser entities.
type TeamUserSelect struct {
	*TeamUserQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (tus *TeamUserSelect) Scan(ctx context.Context, v interface{}) error {
	if err := tus.prepareQuery(ctx); err != nil {
		return err
	}
	tus.sql = tus.TeamUserQuery.sqlQuery(ctx)
	return tus.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (tus *TeamUserSelect) ScanX(ctx context.Context, v interface{}) {
	if err := tus.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (tus *TeamUserSelect) Strings(ctx context.Context) ([]string, error) {
	if len(tus.fields) > 1 {
		return nil, errors.New("ent: TeamUserSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := tus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (tus *TeamUserSelect) StringsX(ctx context.Context) []string {
	v, err := tus.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (tus *TeamUserSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = tus.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{teamuser.Label}
	default:
		err = fmt.Errorf("ent: TeamUserSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (tus *TeamUserSelect) StringX(ctx context.Context) string {
	v, err := tus.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (tus *TeamUserSelect) Ints(ctx context.Context) ([]int, error) {
	if len(tus.fields) > 1 {
		return nil, errors.New("ent: TeamUserSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := tus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (tus *TeamUserSelect) IntsX(ctx context.Context) []int {
	v, err := tus.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (tus *TeamUserSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = tus.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{teamuser.Label}
	default:
		err = fmt.Errorf("ent: TeamUserSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (tus *TeamUserSelect) IntX(ctx context.Context) int {
	v, err := tus.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (tus *TeamUserSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(tus.fields) > 1 {
		return nil, errors.New("ent: TeamUserSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := tus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (tus *TeamUserSelect) Float64sX(ctx context.Context) []float64 {
	v, err := tus.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (tus *TeamUserSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = tus.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{teamuser.Label}
	default:
		err = fmt.Errorf("ent: TeamUserSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (tus *TeamUserSelect) Float64X(ctx context.Context) float64 {
	v, err := tus.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (tus *TeamUserSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(tus.fields) > 1 {
		return nil, errors.New("ent: TeamUserSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := tus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (tus *TeamUserSelect) BoolsX(ctx context.Context) []bool {
	v, err := tus.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (tus *TeamUserSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = tus.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{teamuser.Label}
	default:
		err = fmt.Errorf("ent: TeamUserSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (tus *TeamUserSelect) BoolX(ctx context.Context) bool {
	v, err := tus.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tus *TeamUserSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := tus.sqlQuery().Query()
	if err := tus.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (tus *TeamUserSelect) sqlQuery() sql.Querier {
	selector := tus.sql
	selector.Select(selector.Columns(tus.fields...)...)
	return selector
}
