// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Auth is the predicate function for auth builders.
type Auth func(*sql.Selector)

// Team is the predicate function for team builders.
type Team func(*sql.Selector)

// TeamUser is the predicate function for teamuser builders.
type TeamUser func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
